# Databricks notebook source
# MAGIC %md
# MAGIC # Databricks Container Services
# MAGIC This notebook accesses a file that should only be available on clusters with the custom Docker image generated by the `Dockerfile` and `build.sh` script in this folder.
# MAGIC 
# MAGIC Before running this notebook:
# MAGIC 1. Pull this repo to your local machine
# MAGIC 1. cd into the DCS folder
# MAGIC 1. Run `build.sh`
# MAGIC 1. [Enable Databricks Container Services](https://learn.microsoft.com/en-us/azure/databricks/administration-guide/clusters/container-services)
# MAGIC 1. [Create a cluster that uses the custom Docker image](https://learn.microsoft.com/en-us/azure/databricks/clusters/custom-containers#step-3-launch-your-cluster)
# MAGIC 1. Run this notebook

# COMMAND ----------

# MAGIC %sh
# MAGIC cat /hello.txt

# COMMAND ----------


